import path from "node:path";
import { readFileIfExists, projectName } from "./project.js";
import { depVersion } from "./addon-versions.js";
import {
  packageJsonChange, wranglerChange, fileChange, appendLineChange, ensureHeadersChange
} from "./addon-changes.js";
import { integrationDoc } from "./addon-spec.js";
import {
  type JsonObject, today, addUniqueStrings, upsertArrayObject, upsertDurableObjectMigration, asObject
} from "./addon-utils.js";
import type { ChangeSet, DoctorReport, PlannedChange, ProjectContext } from "./types.js";

export function shouldPatchOpenNext(report: DoctorReport): boolean {
  const patchableIds = new Set([
    "missing-opennext",
    "missing-wrangler-config",
    "missing-nodejs-compat",
    "missing-global-fetch-strictly-public"
  ]);
  return report.issues.some((candidate) => patchableIds.has(candidate.id));
}

// shared OpenNext worker helpers. Used by both this module (next/isr) and the
// Cloudflare binding add-ons (durable-object/workflow) that must export classes
// from a custom worker entry. Lives here to keep the dependency edge one-way.
export function configureOpenNextMainIfNeeded(ctx: ProjectContext, config: JsonObject): void {
  config.$schema = config.$schema ?? "node_modules/wrangler/config-schema.json";
  config.name = config.name ?? projectName(ctx);
  config.compatibility_date = config.compatibility_date ?? today();

  if (ctx.framework !== "nextjs") return;

  config.main = "cloudflare-worker.ts";
  config.compatibility_flags = addUniqueStrings(config.compatibility_flags, [
    "nodejs_compat",
    "global_fetch_strictly_public"
  ]);
  config.assets = {
    directory: ".open-next/assets",
    binding: "ASSETS"
  };
  config.services = upsertArrayObject(config.services, "binding", {
    binding: "WORKER_SELF_REFERENCE",
    service: String(config.name)
  });
}

export async function customOpenNextWorkerChange(
  ctx: ProjectContext,
  exportsToAdd: Array<{ exportName: string; sourcePath: string }>,
  reason: string
): Promise<PlannedChange> {
  const relativePath = "cloudflare-worker.ts";
  const before = await readFileIfExists(path.join(ctx.cwd, relativePath));
  const exportLines = exportsToAdd.map((item) => {
    const source = `./${item.sourcePath.replace(/\.ts$/, "")}`;
    return `export { ${item.exportName} } from "${source}";`;
  });

  if (!before) {
    return {
      path: relativePath,
      before,
      after: customOpenNextWorker(exportLines),
      reason
    };
  }

  const missing = exportLines.filter((line) => !before.includes(line));
  if (missing.length === 0) {
    return {
      path: relativePath,
      before,
      after: before,
      reason
    };
  }

  return {
    path: relativePath,
    before,
    after: `${before.replace(/\n?$/, "\n")}${missing.join("\n")}\n`,
    reason
  };
}

function customOpenNextWorker(exportLines: string[]): string {
  return `// @ts-ignore .open-next/worker.js is generated by @opennextjs/cloudflare at build time.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch
} satisfies ExportedHandler<CloudflareEnv>;

${exportLines.join("\n")}
`;
}

function openNextConfig(): string {
  return `import { defineCloudflareConfig } from "@opennextjs/cloudflare";

export default defineCloudflareConfig({});
`;
}

export async function nextOpenNextAddOn(ctx: ProjectContext): Promise<ChangeSet> {
  if (!ctx.packageJson) {
    return {
      status: "error",
      title: "Cannot patch project without package.json",
      changes: [],
      warnings: [],
      nextActions: ["Create a package.json first."]
    };
  }

  const changes: PlannedChange[] = [];
  changes.push(await packageJsonChange(ctx, "Add OpenNext Cloudflare dependencies and scripts", (pkg) => {
    pkg.dependencies = pkg.dependencies ?? {};
    pkg.devDependencies = pkg.devDependencies ?? {};
    pkg.scripts = pkg.scripts ?? {};

    pkg.dependencies["@opennextjs/cloudflare"] = pkg.dependencies["@opennextjs/cloudflare"] ?? depVersion("@opennextjs/cloudflare");
    pkg.devDependencies.wrangler = pkg.devDependencies.wrangler ?? depVersion("wrangler");
    pkg.devDependencies["@cloudflare/workers-types"] = pkg.devDependencies["@cloudflare/workers-types"] ?? depVersion("@cloudflare/workers-types");

    pkg.scripts.build = pkg.scripts.build ?? "next build";
    pkg.scripts.preview = "opennextjs-cloudflare build && opennextjs-cloudflare preview";
    pkg.scripts.deploy = "opennextjs-cloudflare build && opennextjs-cloudflare deploy";
    pkg.scripts.upload = "opennextjs-cloudflare build && opennextjs-cloudflare upload";
    pkg.scripts["cf-typegen"] = "wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts";
  }));

  changes.push(await wranglerChange(ctx, "Configure OpenNext Worker entry, assets, and compatibility flags", (config) => {
    config.$schema = config.$schema ?? "node_modules/wrangler/config-schema.json";
    config.name = config.name ?? projectName(ctx);
    config.main = ".open-next/worker.js";
    config.compatibility_date = config.compatibility_date ?? today();
    config.compatibility_flags = addUniqueStrings(config.compatibility_flags, [
      "nodejs_compat",
      "global_fetch_strictly_public"
    ]);
    config.assets = {
      directory: ".open-next/assets",
      binding: "ASSETS"
    };
    config.services = upsertArrayObject(config.services, "binding", {
      binding: "WORKER_SELF_REFERENCE",
      service: String(config.name)
    });
  }));

  changes.push(await fileChange(ctx, "open-next.config.ts", openNextConfig(), "Add explicit OpenNext Cloudflare config"));
  changes.push(await appendLineChange(ctx, ".dev.vars", "NEXTJS_ENV=development", "Set local Next.js env for OpenNext dev bindings"));
  changes.push(await appendLineChange(ctx, ".gitignore", ".open-next", "Ignore OpenNext build output"));
  changes.push(await ensureHeadersChange(ctx));

  return {
    status: "planned",
    title: "Add OpenNext Cloudflare support",
    changes: changes.filter((change) => change.before !== change.after),
    warnings: [
      "This does not run npm install. Install dependencies after applying patches.",
      "If your app exports runtime = \"edge\", remove it manually before deploy."
    ],
    nextActions: [
      "npm install",
      "npm run cf-typegen",
      "flarecel verify --json",
      "npm run preview"
    ]
  };
}

// ISR / incremental cache (verified against opennext.js.org/cloudflare/caching, small-site combo).
export async function isrAddOn(ctx: ProjectContext): Promise<ChangeSet> {
  if (ctx.framework !== "nextjs") {
    return {
      status: "error",
      title: "ISR cache requires a Next.js project",
      changes: [],
      warnings: [`Detected framework: ${ctx.framework}. OpenNext incremental cache applies to Next.js.`],
      nextActions: ["flarecel doctor --json"]
    };
  }

  const bucket = `${projectName(ctx)}-inc-cache`;
  const database = `${projectName(ctx)}-tag-cache`;

  const changes = [
    await fileChange(ctx, "open-next.config.ts", isrOpenNextConfig(), "Enable R2 incremental cache, DO queue, and D1 tag cache for ISR"),
    await wranglerChange(ctx, "Add ISR cache bindings (R2 + DO queue + D1 tag cache)", (config) => {
      config.r2_buckets = upsertArrayObject(config.r2_buckets, "binding", {
        binding: "NEXT_INC_CACHE_R2_BUCKET",
        bucket_name: bucket
      });
      const durableObjects = asObject(config.durable_objects);
      durableObjects.bindings = upsertArrayObject(durableObjects.bindings, "name", {
        name: "NEXT_CACHE_DO_QUEUE",
        class_name: "DOQueueHandler"
      });
      config.durable_objects = durableObjects;
      config.migrations = upsertDurableObjectMigration(config.migrations, "v1-isr-cache", "DOQueueHandler");
      config.d1_databases = upsertArrayObject(config.d1_databases, "binding", {
        binding: "NEXT_TAG_CACHE_D1",
        database_name: database,
        database_id: "replace-with-d1-database-id"
      });
      config.services = upsertArrayObject(config.services, "binding", {
        binding: "WORKER_SELF_REFERENCE",
        service: String(config.name ?? projectName(ctx))
      });
    }),
    await fileChange(ctx, "docs/flarecel-isr.md", isrDoc(bucket, database), "Explain the ISR cache add-on")
  ].filter((change) => change.before !== change.after);

  return {
    status: "planned",
    title: "Add OpenNext ISR incremental cache",
    changes,
    warnings: [
      "Requires the OpenNext adapter (run `flarecel add next-opennext` first if missing).",
      "Create the R2 bucket and D1 database before deploy, and copy the D1 database_id into wrangler.jsonc.",
      "The D1 tag cache is only needed for on-demand revalidation (revalidateTag/revalidatePath)."
    ],
    nextActions: [
      `wrangler r2 bucket create ${bucket}`,
      `wrangler d1 create ${database}`,
      "Copy the returned database_id into wrangler.jsonc.",
      "npm run cf-typegen",
      "flarecel verify --json"
    ]
  };
}

function isrOpenNextConfig(): string {
  return `import { defineCloudflareConfig } from "@opennextjs/cloudflare";
import r2IncrementalCache from "@opennextjs/cloudflare/overrides/incremental-cache/r2-incremental-cache";
import doQueue from "@opennextjs/cloudflare/overrides/queue/do-queue";
import d1NextTagCache from "@opennextjs/cloudflare/overrides/tag-cache/d1-next-tag-cache";

export default defineCloudflareConfig({
  incrementalCache: r2IncrementalCache,
  queue: doQueue,
  tagCache: d1NextTagCache
});
`;
}

function isrDoc(bucket: string, database: string): string {
  return integrationDoc("OpenNext ISR incremental cache", `Wires Next.js ISR/revalidation on Cloudflare using the OpenNext small-site combo:

- R2 incremental cache (\`NEXT_INC_CACHE_R2_BUCKET\` -> \`${bucket}\`)
- Durable Object revalidation queue (\`NEXT_CACHE_DO_QUEUE\`, class \`DOQueueHandler\`)
- D1 tag cache (\`NEXT_TAG_CACHE_D1\` -> \`${database}\`, only for on-demand revalidation)

Verified against opennext.js.org/cloudflare/caching. Create the R2 bucket and D1 database, then copy the database_id into wrangler.jsonc before deploy.`);
}
