import { promises as fs } from "node:fs";
import path from "node:path";
import type { ChangeSet, PackageManager, ProjectContext } from "./types.js";

export interface CiOptions {
  provider?: string;
  branch?: string;
}

const WORKFLOW_PATH = ".github/workflows/deploy.yml";
const SECRET_NAME = "CLOUDFLARE_API_TOKEN";

/**
 * Generate a CI workflow that deploys the project to Cloudflare on push.
 *
 * Like every file-changing command, this returns a ChangeSet and never writes
 * directly — the caller routes it through the dry-run / `--apply --yes` gate.
 * Today only GitHub Actions is supported; the token stays a repo secret and is
 * never read or written by Flarecel.
 */
export async function createCiChangeSet(ctx: ProjectContext, options: CiOptions = {}): Promise<ChangeSet> {
  const provider = (options.provider ?? "github").toLowerCase();
  if (provider !== "github") {
    return {
      status: "error",
      title: `Unsupported CI provider: ${provider}`,
      changes: [],
      warnings: [`Only "github" is supported right now (GitHub Actions).`],
      nextActions: ["flarecel ci --provider github --dry-run"]
    };
  }

  const branch = (options.branch ?? "main").trim() || "main";
  const yaml = renderGithubWorkflow(ctx, branch);
  const before = await readIfExists(path.join(ctx.cwd, WORKFLOW_PATH));

  const changes =
    before === yaml
      ? []
      : [
          {
            path: WORKFLOW_PATH,
            before,
            after: yaml,
            reason:
              before === null
                ? "Add a GitHub Actions workflow that deploys to Cloudflare on push."
                : "Update the Cloudflare deploy workflow."
          }
        ];

  const status: ChangeSet["status"] = changes.length === 0 ? "empty" : "planned";

  const warnings = [
    `This workflow needs a ${SECRET_NAME} repository secret. The deploy step fails until it is set.`,
    `Mint it in the Cloudflare dashboard (My Profile -> API Tokens -> "Edit Cloudflare Workers" template), scoped to the target account and zone. Flarecel never reads or writes this token.`
  ];

  const nextActions =
    status === "empty"
      ? ["Workflow already up to date.", `Confirm the ${SECRET_NAME} repo secret is set.`]
      : [
          "flarecel ci --apply --yes",
          `gh secret set ${SECRET_NAME}   # paste the token at the prompt; never commit it`,
          `Push to ${branch} (or use the workflow's "Run workflow" button) to deploy.`
        ];

  return {
    status,
    title: "GitHub Actions \u2014 deploy to Cloudflare on push",
    changes,
    warnings,
    nextActions
  };
}

function renderGithubWorkflow(ctx: ProjectContext, branch: string): string {
  const pm: PackageManager = ctx.packageManager === "unknown" ? "npm" : ctx.packageManager;
  // Next.js/OpenNext deploys run through the project's own `deploy` script
  // (build + wrangler). Everything else uses the official wrangler-action.
  const usesDeployScript = ctx.framework === "nextjs" && Boolean(ctx.packageJson?.scripts?.deploy);

  const steps: string[] = [];
  steps.push(step("Checkout", "actions/checkout@v4"));

  if (pm === "pnpm") steps.push(step("Setup pnpm", "pnpm/action-setup@v4"));
  if (pm === "bun") steps.push(step("Setup Bun", "oven-sh/setup-bun@v2"));

  steps.push(setupNodeStep(pm));
  steps.push(runStep("Install dependencies", installCommand(pm)));

  if (usesDeployScript) {
    steps.push(
      [
        "      - name: Deploy",
        `        run: ${runScript(pm, "deploy")}`,
        "        env:",
        `          ${SECRET_NAME}: \${{ secrets.${SECRET_NAME} }}`
      ].join("\n")
    );
  } else {
    steps.push(
      [
        "      - name: Deploy",
        "        uses: cloudflare/wrangler-action@v3",
        "        with:",
        `          apiToken: \${{ secrets.${SECRET_NAME} }}`,
        "          command: deploy"
      ].join("\n")
    );
  }

  return [
    "# Generated by `flarecel ci`. Deploys to Cloudflare on push.",
    "name: Deploy to Cloudflare",
    "",
    "on:",
    "  push:",
    `    branches: [${branch}]`,
    "  workflow_dispatch: {}",
    "",
    "# Don't run overlapping deploys; newest push wins.",
    "concurrency:",
    "  group: deploy-production",
    "  cancel-in-progress: true",
    "",
    "jobs:",
    "  deploy:",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    steps.join("\n"),
    ""
  ].join("\n");
}

function setupNodeStep(pm: PackageManager): string {
  const lines = [
    "      - name: Setup Node",
    "        uses: actions/setup-node@v4",
    "        with:",
    "          node-version: 20"
  ];
  // setup-node's built-in cache supports npm/pnpm/yarn (not bun).
  if (pm === "npm" || pm === "pnpm" || pm === "yarn") {
    lines.push(`          cache: ${pm}`);
  }
  return lines.join("\n");
}

function installCommand(pm: PackageManager): string {
  if (pm === "pnpm") return "pnpm install --frozen-lockfile";
  if (pm === "yarn") return "yarn install --frozen-lockfile";
  if (pm === "bun") return "bun install --frozen-lockfile";
  return "npm ci";
}

function runScript(pm: PackageManager, script: string): string {
  if (pm === "pnpm") return `pnpm run ${script}`;
  if (pm === "yarn") return `yarn ${script}`;
  if (pm === "bun") return `bun run ${script}`;
  return `npm run ${script}`;
}

function step(name: string, uses: string): string {
  return [`      - name: ${name}`, `        uses: ${uses}`].join("\n");
}

function runStep(name: string, run: string): string {
  return [`      - name: ${name}`, `        run: ${run}`].join("\n");
}

async function readIfExists(target: string): Promise<string | null> {
  try {
    return await fs.readFile(target, "utf8");
  } catch {
    return null;
  }
}
